language:  shell
os: linux
dist: xenial

before_install:
  - sudo apt-get -y install ghp-import
  - make init

script:
  - make check
  - make build

deploy:
  provider: pages:git
  local_dir: _site
  edge: true
#  on:
#after_script:
#  - make publish
