# Site settings
title: Plato Frugal
author: "Cedric Quintes"
description: Food blog for modest and clean recipes.
baseurl: "" 
url: "http://platofrugal.com"

image: assets/ico/apple-touch-icon-180x180.png
# Build settings
markdown: kramdown
category: recetas

permalink: none
sass:
    sass_dir: bower_components/foundation/scss
    style: compressed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - bower.json
    - node_modules/*

